plugins {
    id 'com.android.application'
}

android {
    namespace 'com.wmy.healthcheckin'
    compileSdk 35

    defaultConfig {
        applicationId 'com.wmy.healthcheckin'
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName '2.1'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}
